server:
  port: 8080

loadbalancer:
  servers:
    - id: server-1
      url: http://localhost:8081
      weight: 3
    - id: server-2
      url: http://localhost:8082
      weight: 2
    - id: server-3
      url: http://localhost:8083
      weight: 1
  health-check:
    interval: 5000
    timeout: 2000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.havryliuk.loadbalancer: INFO
